project_name: fanpulse-worldcup-mlops
run_name: dummy_4class

data_path: data/processed/fanpulse_dataset_v2.csv
target_mode: 4class

model_type: dummy
test_size: 0.25
random_state: 42

artifact_name: fanpulse-impression-classifier
register_aliases:
  - latest